name: deploy-chabokan
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: "18"
    - name: update-chabokan
      env:
        CHABOKAN_TOKEN: ${{ secrets.CHABOKAN_TOKEN }}
      run: |
        npm install -g @chabokan.net/cli
        chabok login -t $CHABOKAN_TOKEN
        chabok deploy -s bigtools
